import './bootstrap';
import '@/lib/vendor/autocomplete';
import '@/icons';
import '@/display_constants';
import '@/expr_parser';
import '@/search';
import '@/drag_drop_touch';
import '@/ingredients';
import '@/display';
