/** TS modules imported by bootstrap.ts. */
export const tsModules = {
  redirectFork: '@/redirect_fork',
  loader: '@/loader',
  powders: '@/powders',
  skillpoints: '@/skillpoints',
  damageCalc: '@/damage_calc',
} as const;

/** Classic script paths, loaded in order. */
export const legacy = {
  redirectFork: '/js/redirect_fork.js',
  autoComplete: '/thirdparty/autoComplete.min.js',
  macy: '/thirdparty/macy@2',
  dragDropTouch: '/js/drag_drop_touch.js',
  utils: '/js/utils.js',
  buildUtils: '/js/build_utils.js',
  computationGraph: '/js/computation_graph.js',
  icons: '/js/icons.js',
  powders: '/js/powders.js',
  skillpoints: '/js/skillpoints.js',
  damageCalc: '/js/damage_calc.js',
  displayConstants: '/js/display_constants.js',
  display: '/js/display.js',
  loader: '/js/loader.js',
  loadItem: '/js/load_item.js',
  loadIng: '/js/load_ing.js',
  loadTome: '/js/load_tome.js',
  loadAspect: '/js/load_aspect.js',
  custom: '/js/custom.js',
  craft: '/js/craft.js',
  manaCalc: '/js/mana_calc.js',
  query: '/js/query.js',
  exprParser: '/js/expr_parser.js',
  search: '/js/search.js',
  items: '/js/items.js',
  itemDisplay: '/js/item_display.js',
  item: '/js/item.js',
  crafter: '/js/crafter.js',
  customizer: '/js/customizer.js',
  loadMap: '/js/load_map.js',
  map: '/js/map.js',
  atlas: '/js/atlas.js',
  ingredients: '/js/ingredients.js',
  ingredient: '/js/ingredient.js',
  searchAdv: '/js/search_adv.js',
  itemsAdv: '/js/items_adv.js',
  ingredientsAdv: '/js/ingredients_adv.js',
  dev: '/js/dev.js',
  dpsVis: '/js/debug/dps_vis.js',
  renderComputeGraph: '/js/debug/render_compute_graph.js',
  build: '/js/builder/build.js',
  builderConstants: '/js/builder/builder_constants.js',
  buildEncodeDecode: '/js/builder/build_encode_decode.js',
  atree: '/js/builder/atree.js',
  aspects: '/js/builder/aspects.js',
  builderGraph: '/js/builder/builder_graph.js',
  builder: '/js/builder/builder.js',
  optimize: '/js/builder/optimize.js',
  wynnfoMain: '/wynnfo/scripts/main.js',
} as const;

/** Display page script stack; powders and damage_calc come from tsModules. */
export const displayStack = [
  legacy.buildUtils,
  legacy.displayConstants,
  legacy.display,
  legacy.loader,
  legacy.loadItem,
] as const;

export const searchStack = [
  legacy.query,
  legacy.exprParser,
  legacy.search,
] as const;
