/**
 * Player build, equipment slot, powder, and encoding types.
 */

import type { AspectSpec, AspectTuple, DecodedAspect } from './aspect';
import type { ATree, RenderedATree } from './atree';
import type {
  AttackSpeed,
  BuildStatMap,
  DecodedSkillpoints,
  PowderId,
  PowderString,
  SkillpointCalculationResult,
  SkillpointVector,
} from './stats';

/** Minimal equipment reference — full item types live in item.ts. */
export interface BuildItemRef {
  statMap: Map<string, unknown>;
}

/** Equipment slot indices in the builder equipment array (excludes weapon). */
export enum EquipmentSlot {
  Helmet = 0,
  Chestplate = 1,
  Leggings = 2,
  Boots = 3,
  Ring1 = 4,
  Ring2 = 5,
  Bracelet = 6,
  Necklace = 7,
}

/** Total wearable equipment pieces including weapon (9 slots). */
export const EQUIPMENT_SLOT_COUNT = 9;

/** Powderable equipment indices: helmet, chest, legs, boots, weapon. */
export const POWDERABLE_EQUIPMENT_INDICES = [0, 1, 2, 3, 8] as const;

export type PowderableEquipmentIndex =
  (typeof POWDERABLE_EQUIPMENT_INDICES)[number];

/** Five powder sets aligned with powderable slots (not tomes). */
export type BuildPowderSets = [
  PowderId[] | PowderString,
  PowderId[] | PowderString,
  PowderId[] | PowderString,
  PowderId[] | PowderString,
  PowderId[] | PowderString,
];

/** Numeric powder sets used during binary encoding. */
export type EncodedPowderSets = PowderId[][];

export const TOME_SLOT_COUNT = 14;

/** Kind flag written per equipment piece in binary encoding. */
export enum EquipmentKind {
  Normal = 0,
  Crafted = 1,
  Custom = 2,
}

/** Player build produced by the Build class. */
export interface PlayerBuild {
  level: number;
  /** All worn pieces: equipment + tomes + weapon. */
  items: BuildItemRef[];
  /** Helmet through necklace (8 pieces). */
  equipment: BuildItemRef[];
  tomes: BuildItemRef[];
  weapon: BuildItemRef;

  availableSkillpoints: number;
  /** Stat maps in equip order (excludes tomes / NONE). */
  equip_order: Map<string, unknown>[];
  /** Manually assigned skillpoint deltas (etwfa order). */
  base_skillpoints: SkillpointVector;
  /** Final skillpoints after items and sets. */
  total_skillpoints: SkillpointVector;
  /** Sum of base_skillpoints. */
  assigned_skillpoints: number;
  activeSetCounts: Map<string, number>;
  total_item_skillpoints: SkillpointVector;

  statMap: BuildStatMap;
}

/** Inputs passed to encodeBuild(). */
export interface BuildEncodeParams {
  build: PlayerBuild;
  powders: EncodedPowderSets;
  skillpoints: SkillpointVector;
  atree: ATree;
  atree_state: RenderedATree;
  aspects: AspectTuple[];
}

/** Partial decode result before UI population. */
export interface DecodedBuild {
  equipment: Array<string | null>;
  powders: PowderString[];
  tomes: Array<string | null>;
  skillpoints: DecodedSkillpoints;
  level: number;
  aspects: DecodedAspect[];
  /** Remaining bitvector cursor payload for atree decode. */
  atree_data?: unknown;
}

/** Legacy hash decode defaults. */
export interface LegacyDecodedBuild extends DecodedBuild {
  equipment: Array<string | null>;
  powdering: PowderString[];
}

/** Flag values from encoding_consts.json (subset used by build encoder). */
export interface EncodingConstants {
  EQUIPMENT_KIND: { NORMAL: number; CRAFTED: number; CUSTOM: number; BITLEN: number };
  EQUIPMENT_NUM: number;
  ITEM_ID_BITLEN: number;
  TOMES_FLAG: { NO_TOMES: number; HAS_TOMES: number; BITLEN: number };
  TOME_SLOT_FLAG: { UNUSED: number; USED: number; BITLEN: number };
  TOME_NUM: number;
  TOME_ID_BITLEN: number;
  SP_FLAG: { AUTOMATIC: number; ASSIGNED: number; BITLEN: number };
  SP_ELEMENT_FLAG: { ELEMENT_UNASSIGNED: number; ELEMENT_ASSIGNED: number; BITLEN: number };
  SP_TYPES: number;
  MAX_SP_BITLEN: number;
  LEVEL_FLAG: { MAX: number; OTHER: number; BITLEN: number };
  LEVEL_BITLEN: number;
  MAX_LEVEL: number;
  ASPECTS_FLAG: { NO_ASPECTS: number; HAS_ASPECTS: number; BITLEN: number };
  ASPECT_SLOT_FLAG: { UNUSED: number; USED: number; BITLEN: number };
  NUM_ASPECTS: number;
  ASPECT_ID_BITLEN: number;
  ASPECT_TIER_BITLEN: number;
  EQUIPMENT_POWDERS_FLAG: { NO_POWDERS: number; HAS_POWDERS: number; BITLEN: number };
  POWDER_REPEAT_OP: { REPEAT: number; NO_REPEAT: number; BITLEN: number };
  POWDER_REPEAT_TIER_OP: { REPEAT_TIER: number; CHANGE_POWDER: number; BITLEN: number };
  POWDER_CHANGE_OP: { NEW_POWDER: number; NEW_ITEM: number; BITLEN: number };
  POWDER_ID_BITLEN: number;
  POWDER_WRAPPER_BITLEN: number;
  POWDER_TIERS: number;
  POWDER_ELEMENTS: string[];
}

/** Mapping from powderable equipment index to build_powders array index. */
export type PowderableIndexMap = Map<number, number>;

/** Share-text lines generated by shareBuild(). */
export interface BuildShareInfo {
  url: string;
  equipmentNames: string[];
  weaponLine: string;
  hasTomes: boolean;
  hasAspects: boolean;
}

/** Constructor arguments for the Build class. */
export interface PlayerBuildParams {
  level: number;
  equipment: BuildItemRef[];
  tomes: BuildItemRef[];
  weapon: BuildItemRef;
  /** Equipment in wynn equip order for skillpoint calculation. */
  wynnOrderEquipment: BuildItemRef[];
}

/** Re-export skillpoint result shape for convenience at build boundary. */
export type { SkillpointCalculationResult, SkillpointVector, AttackSpeed };

/** Aspect slot input: aspect spec paired with selected tier (1-based). */
export type { AspectSpec, AspectTuple };
